apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend-svc
  name: udagram-frontend
spec:
  ports:
  - name: "8100"
    port: 80
    protocol: TCP
  selector:
    app: udagram-frontend